### ISSUE TITLE
Cannot add second bridge validator

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/token-bridge#139]
Hi, guys! I've deployed a new xDAI-like chain recently with one ERC-TO-NATIVE bridge. 
First I deployed the network and the bridge contracts and after that get the info that I will need 2 validators not one.
Since there was no launched validators still, I simply called the `addValidator` method on both sides of the bridge and increased `requiredSignatures` from 1 to 2.
However, when I launched the bridge only one of the validators were able to validate the transactions. Either I got the error, or the contract call, made by one of the validators failed.
Here is the examples of validating transactions from both validators after I send the ERC tokens to home network for the first time:
https://explorer-xdai.makerfoundation.com/tx/0xaa52cafd56b796ac88b025d81a0f1b2b60f89ca5785c99b434d31fa77e62dd9f
https://explorer-xdai.makerfoundation.com/tx/0x55f429c0e3845b7cd87e06719470b0cd8f7d7db595d6001ee856d52793fdefc6
In the [attached file](https://github.com/poanetwork/token-bridge/files/3045380/bridge_affirmation.txt) you can get the 
example of the error I got when tried to send tokens for the second time:
Can you help me to debug this, please? I spent hours and hours on trying to find the roots of that issue.

Many thanks in advance.

**Comment by ArseniiPetrovich** [comment]
Issuee might not lie in the validator itself. I decreased the number of required signatures to 1 and still cannot transfer anything through bridge :(

**Comment by akolotov** [comment]
I see that the issue happens within `estimateGas` call. At this moment `executeAffirmation` of the bridge contract at Home is being tried to invoked to calculate the gas consumed:
```solidity
    function executeAffirmation(address recipient, uint256 value, bytes32 transactionHash) external onlyValidator {
        if (affirmationWithinLimits(value)) {
            bytes32 hashMsg = keccak256(abi.encodePacked(recipient, value, transactionHash));
            bytes32 hashSender = keccak256(abi.encodePacked(msg.sender, hashMsg));
            // Duplicated affirmations
            require(!affirmationsSigned(hashSender));
            setAffirmationsSigned(hashSender, true);


            uint256 signed = numAffirmationsSigned(hashMsg);
            require(!isAlreadyProcessed(signed));
            // the check above assumes that the case when the value could be overflew will not happen in the addition operation below
            signed = signed + 1;


            setNumAffirmationsSigned(hashMsg, signed);


            emit SignedForAffirmation(msg.sender, transactionHash);


            if (signed >= requiredSignatures()) {
                // If the bridge contract does not own enough tokens to transfer
                // it will couse funds lock on the home side of the bridge
                setNumAffirmationsSigned(hashMsg, markAsProcessed(signed));
                require(onExecuteAffirmation(recipient, value));
                emit AffirmationCompleted(recipient, value, transactionHash);
            }
        } else {
            onFailedAffirmation(recipient, value, transactionHash);
        }
    }
```
the TokenBridge oracle catches the error (if a revert happened) and tries to understand possible reason of the revert operation.
If we see the message like `Unknown error while processing message`, most probably it means that the issue happens during execution of `require(onExecuteAffirmation(recipient, value));`.
The code of this method is the following:
```
    function onExecuteAffirmation(address _recipient, uint256 _value) internal returns(bool) {
        setTotalExecutedPerDay(getCurrentDay(), totalExecutedPerDay(getCurrentDay()).add(_value));
        IBlockReward blockReward = blockRewardContract();
        require(blockReward != address(0));
        blockReward.addExtraReceiver(_value, _recipient);
        return true;
    }
```
So, it means that revert could happen if the block reward contract is not set properly or the call of `addExtraReceiver` fails. 

In order to proceed with further investigation could you share what version of POA consensus contract you used? Also please confirm that the bridge contracts were taken from the `master` branch.

**Comment by ArseniiPetrovich** [comment]
@akolotov 
Oh, yes, that is the thing I forgot to mention - there was a bug with configuring BlockReward contract address in bridge contract, however I added it manually via MEW call. 
And bridge contracts were taken from develop branch by accident, my this cause the issue? How can I fix it?
Where can I get the version of consensus contracts?

**Comment by akolotov** [comment]
Hmm... What exact approach you used to change the block reward contract? Did you transact to `Proxy` or `Implementation` contract?

**Comment by ArseniiPetrovich** [comment]
I used the `HomeBridge` address from `bridgeDeploymentResult.json` file and executed the method `setBlockRewardContract` with the address of BlockReward as an argument. I got the address from `contracts` file after ConsensusContracts deployment.

**Comment by akolotov** [comment]
May I have a RPC URL to a node in that chain to troubleshoot the issue?

**Comment by ArseniiPetrovich** [comment]
Sure. Check your DM, shared privately.

**Comment by akolotov** [comment]
@ArseniiPetrovich 
Seems I understood the issue. If I look at the following fields of contract:
```
executionDailyLimit: 1
executionMaxPerTx: 0
```
the value here are too small. Usually they should be the same as `dailyLimit` and `maxPerTx`. Now, since amount of token is more than limits, new coins are not minted.

Consider to increase these limits by calling `setExecutionDailyLimit` and `setExecutionMaxPerTx`. After changing the values you could reset block of the working to watch for `affirmation-request`. The worker could start again from very beginning - from the block 34517.

**Comment by ArseniiPetrovich** [comment]
Great, thank you! It is working now.
