### ISSUE TITLE
Docker containers don't connect

### ISSUE THREAD

**Issue by jannikluhn** [poanetwork/token-bridge#142]
I'm trying to run the token bridge (erc to native if that's relevant) with `docker-compose`, but there seem to be some connection issues. Here's what I did:

- setup two Parity nodes with open RPC ports on two local POA test chains
- deployed the bridge contracts, including the reward contract
- cloned this repository
- configured the `.env` file
- ran the following commands as described in the readme:

```
VALIDATOR_ADDRESS=0x2b5ad5c4795c026514f8317c7a215e218dccd6cf
VALIDATOR_ADDRESS_PRIVATE_KEY=0x0000000000000000000000000000000000000000000000000000000000000002
docker-compose up -d --build
docker-compose up --detach
```

This succeeded in setting up a bunch of docker containers (`senderhome`, `collected`, `request`, `senderforeign`, `affirmation`, `redis` and `rabbit`). However, the logs of `senderhome`, `collected`, `request` and `senderforeign` are filled with messages like this:

```
{"level":50,"time":1556124508636,"msg":"Disconnected from redis","validator":"0x2b5ad5c4795c026514f8317c7a215e218dccd6cf","name":"watcher-erc-native-affirmation-request","v":1}
{"level":50,"time":1556124509023,"msg":"Disconnected from amqp Broker","validator":"0x2b5ad5c4795c026514f8317c7a215e218dccd6cf","name":"watcher-erc-native-affirmation-request","v":1}
```

The logs of `redis` shows some warnings, but claims to be `Ready to accept connections`. And `rabbit` `started TCP listener on [::]:5672`.

**Comment by akolotov** [comment]
Hi! as per instruction you need to run either `VALIDATOR_ADDRESS=<validator address> VALIDATOR_ADDRESS_PRIVATE_KEY=<validator address private key> docker-compose up -d --build` or `VALIDATOR_ADDRESS=<validator address> VALIDATOR_ADDRESS_PRIVATE_KEY=<validator address private key> docker-compose up --detach`. Not both at the same time since the first command already run the containers after building them.

Could you stop the containers by `docker-compose down` in the directory where `docker-compose.yml` is located, make sure that `docker-compose ps` outputs nothing, start them again by `VALIDATOR_ADDRESS=<validator address> VALIDATOR_ADDRESS_PRIVATE_KEY=<validator address private key> docker-compose up --detach` wait for 10-20 seconds and send us entire output of the command `docker-compose logs`

**Comment by jannikluhn** [comment]
Thanks for your help. I've followed your steps, but it didn't seem to have changed anything. Here's the complete log output: https://gist.github.com/jannikluhn/c498a033cf0a1fbafc3edcc5260ca93c

**Comment by akolotov** [comment]
Thanks. Could you share your `.env` file?

**Comment by akolotov** [comment]
I think the issue is that you are using local parity nodes accessible through `localhost`. At the same time the token bridge containers are running in their own subnets so they have no access to the processes run on the host machine.
You ether need to modify `docker-compose.xml` to run parity clients accessible by the token bridge processes or run the token bridge by NPM (https://github.com/poanetwork/token-bridge#npm) without `docker-compose`.

**Comment by akolotov** [comment]
@jannikluhn are you still experiencing the issue?

**Comment by jannikluhn** [comment]
No, everything seems to be working now. Based on your suggestion, we've created two new docker networks for the bridge containers to connect to the two Parity nodes. We've edited the docker compose file accordingly.

However, Docker seems to have been misconfigured on our machine as well, which might have been the actual source of the issue. Updating and rebooting helped here.

Anyways, thanks for your quick and helpful response!
