### ISSUE TITLE
Update documentation for current support of contracts

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/token-bridge#53]
We have a few versions already in this project.
1. Native to ERC based on v2 branch contracts
2. Native to ERC based on refactor_v1 branch
3. ERC to ERC based on v2 branch contracts
4. ERC to ERC based on refactor_v1 branch

We need a way to have easy to follow documentation on how to use the bridge for each contract's version

**Comment by fvictorio** [comment]
I think the easiest solution is to have the contracts a submodule. I know git submodules can be problematic, but well used they are useful. Besides, another POA project (Token Wizard) is already using them for the contracts, and the bridge itself has a submodule with the contracts in the e2e directory. What do you think?

**Comment by akolotov** [comment]
It is not applicable any more, since we merge everything in the master branch. The token bridge could use the version stored in the contract to identify the scope of the features that can be used with this contracts revision. The documentation was updated to unify the process of the token bridge instance running.
